config/routes.rb
Sample::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#index'

  resources :pages

  resources :angular, :path => '/angular'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/page.rb
class Page < ActiveRecord::Base

  before_save :set_slug_if_blank
  before_save :remove_cache
  before_destroy :remove_cache
  def self.avalaible_positions
    total = self.count
    if total > 0
      (1..(total + 1)).to_a.map{|s| ["# #{s}", s]}
    else
      [["# 1", 1]]
    end
  end

  def self.active
    self.where(active: true)
  end

  validates :title, presence: true

  validates :slug, uniqueness: { :case_sensitive => false }, format: {with: /\A[A-Za-z\d_]+\z/, :message => I18n.t('activerecord.page.slug_not_in_format')},
            allow_blank: true

  def set_slug_if_blank
    if self.slug.blank?
      self.slug = self.title.downcase.tr(' ', '_')
    end
  end

  def remove_cache
    Rails.cache.clear
  end
end

app/controllers/angular_controller.rb
class AngularController < ApplicationController
  def index
  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  respond_to :html, :json

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  #check authentication token only for json requests
  before_action :json_authentication_token

  # GET /pages
  # GET /pages.json
  def index
    @pages = Rails.cache.fetch("page/#{params[:page] || 0}",expires_in: 2.hours) do
      pages = Page.order('id DESC').page( params[:page] ).per(10)
      Kaminari::PaginatableArray.new(pages.to_a, limit: pages.limit_value, offset: pages.offset_value, total_count: pages.total_count)
    end

    respond_with @pages
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  def open
    @page = Page.find_by(url: params[:url])
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to pages_path, notice: I18n.t('page_conntroller.created') }
        format.json { render json: @page, status: :created, location: pages_path }
      else
        format.html {
          flash[:alert] = @page.errors.full_messages.to_sentence
          render :action => 'new'
        }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to pages_path, notice: I18n.t('page_conntroller.updated') }
        format.json { render json: @page, status: :created, location: pages_path}
      else
        format.html {
          flash[:alert] = @page.errors.full_messages.to_sentence
          render :action => 'new'
        }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { render json: @page, status: :ok }
    end
  end

  private

  def json_authentication_token
    if request.format.json?
      auth_token = request.headers['Authorization']
      if auth_token
        authenticate_with_auth_token auth_token
      else
        authentication_error
      end
    end
  end

  def authenticate_with_auth_token auth_token
    unless auth_token == ENV['JSON_AUTHENTICATION_TOKEN']
      authentication_error
    end
  end

  def authentication_error
    render json: {error: I18n.t('unauthorized')}, status: 401
  end

  def set_page
    @page = Page.find(params[:id])
  end

  def page_params
    params.require(:page).permit(:title, :description, :slug, :body, :active, :author, :position, :insert_date, :update_date)
  end

end

app/helpers/angular_helper.rb
module AngularHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = ['danger', 'info', 'success', 'warning']

  #class alert-error now is alert-danger in bootstrap 3.0

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = 'success' if type == 'notice'
      type = 'danger'   if type == 'alert'
      next unless ALERT_TYPES.include?(type)
      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                               msg.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/views/angular/index.html.erb
<div data-ng-controller="PagesController">
<div class="page-header">
		<div class="row">
			<div class="col-md-6 col-sm-6">
				<h1>Página</h1>
			</div>
		</div>
	</div>

	<div class="row">
	<div class="col-md-12">

		<a href="" data-toggle="modal" data-target="#myModal" class="new-btn">CADASTRAR Página</a>


		<div class="panel panel-default margin-panel">
			<!-- Default panel contents -->
			<div class="panel-heading">Páginas do sistema</div>

			<!-- Table -->
			<table class="table">
				<thead>
					<tr>

						<th>Título</th>
            <th>Slug</th>
						<th>Ações</th>
					</tr>
				</thead>

				<tbody>
            <tr class="news-list" data-ng-repeat="page in pages">

                <td><input type="text" data-ng-model="page.title"></td>
                <td><input type="text" data-ng-model="page.slug"></td>

              <td><ul>

                        <li title="Editar" data-ng-click="editPage(page) ; $event.preventDefault(); $event.stopPropagation()" rel="tooltip" class="inline icon edit_member_link ">
                            <a href="" >
                                <i class="glyphicon glyphicon-pencil"></i>
                                <span style="display:none">Atualizar</span>
                            </a>
                        </li>
                        <li title="Remover" rel="tooltip" class="inline icon delete_member_link ">
                            <a class="" data-ng-click="removePage(page)">
                                <i class="glyphicon glyphicon-remove"></i>
                                <span style="display:none">Remover</span>
                            </a>
                        </li>
                </ul></td>
            </tr>
				</tbody>
			</table>
		</div>
		</div>
	</div>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Nova Página</h4>
        </div>
        <div class="modal-body">
          <div>
            <lavel>Nome</lavel>
          <input type="text" data-ng-model="newPage.title">
          </div>
          <div>
            <lavel>Slug:</lavel>
            <input type="text" data-ng-model="newPage.slug">
          </div>
          <div>
            <label>Conteúdo:</label>
            <textarea type="text" data-ng-model="newPage.body"></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" data-ng-click="createPage()">Savar</button>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/home/index.html.erb
<div class="page-header">
  <div class="row">
    <div class="col-md-6 col-sm-6">
      <h1>Home</h1>
    </div>
  </div>
</div>


<!-- Stats -->


<!-- Atalhos -->
<div class="row">
  <div class="col-md-5">
    <div class="panel panel-default shortcuts">

      <div class="panel-heading">Acesso Rápido</div>
      <div class="panel-body">

        <a href="/pages/new" class="shortcut" title="Cadastrar Página">
          <i class="glyphicon glyphicon-user"></i>
          <span class="shortcut-label">Cadastrar Página</span>
        </a>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ignition</title>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato:100,300,400,700">
  <%= stylesheet_link_tag  "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>


<header class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Menu</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a href="/admin" class="navbar-brand" title="GoldGroup">Ignition</a>
  </div>
  <div class="collapse navbar-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li>
        <a href="javascript://" title="Olá, Luis">Olá, Ignition</a>
      </li>
      <li>
      </li>
    </ul>
  </div>
</header>
<aside class="sidebar col-md-2">
  <nav id="sidebar-menu" role="complementary">
    <ul>
      <li class="active">
        <a href="/pages" title="Home"><i class="glyphicon glyphicon-home"></i><span>Páginas</span></a>
      </li>

    </ul>
  </nav>
</aside>

<div class="content col-md-10">
  <%= bootstrap_flash %>
  <%= yield %>
</div>



<%= javascript_include_tag "application", "data-turbolinks-eval" => false %>
</body>
</html>

app/views/pages/_form.html.erb
       <%= form_for(@page, :html => {:class => 'form-horizontal padding-form', :multipart => true}) do |f| %>
			<br>
			<fieldset>

              <div class="control-group">
                <label class="control-label" for="title">Nome</label>
                <div class="controls">
                  <%= f.text_field :title, class: 'form-control input-md', placeholder: 'Título da Página' %>

                </div>
              </div>

              <div class="control-group">
                <label class="control-label" for="title">Descrição</label>
                <div class="controls">
                  <%= f.text_field :description, class: 'form-control input-md', placeholder: 'Descrição da Página' %>

                </div>
              </div>

              <div class="control-group">
                <label class="control-label" for="title">Link</label>
                <div class="controls">
                <%= f.text_field :slug, class: 'form-control input-md', placeholder: 'Slug da Página' %>

                </div>
              </div>

            <div class="control-group">
                <label for="cel" class="control-label">Ativar:</label>
                <div class="controls">
                  <%= f.check_box(:active) %>
                </div>
             </div>

              <!-- Text input-->
              <div class="control-group">
                <label class="control-label" for="resume">Posição</label>
                <div class="controls">
                  <%= f.select(:position,  options_for_select(Page.avalaible_positions), class: 'form-control input-sm') %>

                </div>
              </div>

              <!-- Text input-->
              <div class="control-group">
                <label class="control-label" for="title">Conteúdo</label>
                <div class="controls">
                  <%= f.cktext_area :body, :as => :ckeditor, class: 'ckeditor' %>
                </div>
              </div>

              <div class="col-md-12" style="margin-top:10px;position:relative; right:10px;">
				        <button class="btn btn-primary btn-function">Cadastrar</button>
              </div>

			</fieldset>
	   <% end %>

app/views/pages/edit.html.erb
	<div class="page-header">
		<div class="row">
			<div class="col-md-6 col-sm-6">
				<h1>Página</h1>
			</div>
		</div>
	</div>

	<div class="row">
	<div class="col-md-12">

		<%= link_to "VOLTAR", :back, class: "new-btn" %>



		<div class="panel panel-default margin-panel">
			<!-- Default panel contents -->
			<div class="panel-heading">Editar Página</div>

		<div class="row">
            <%= render 'form' %>
		</div>

		</div>

		</div>
		</div>

app/views/pages/index.html.erb
	<div class="page-header">
		<div class="row">
			<div class="col-md-6 col-sm-6">
				<h1>Página</h1>
			</div>
		</div>
	</div>

	<div class="row">
	<div class="col-md-12">

		<a href="/pages/new" class="new-btn">CADASTRAR Página</a>


		<div class="panel panel-default margin-panel">
			<!-- Default panel contents -->
			<div class="panel-heading">Páginas do sistema</div>

			<!-- Table -->
			<table class="table">
				<thead>
					<tr>

						<th>Título</th>
            <th>Slug</th>
						<th>Ações</th>
					</tr>
				</thead>

				<tbody>
                    <% @pages.each{ |page| %>
                        <tr class="news-list">

                            <td><%= page.title %></td>
                            <td><%= page.slug %></td>

                          <td><ul>

                                    <li title="Editar" rel="tooltip" class="inline icon edit_member_link ">
                                        <a class="" href="<%= edit_page_path(id: page.id) %>">
                                            <i class="glyphicon glyphicon-pencil"></i>
                                            <span style="display:none">Editar</span>
                                        </a>
                                    </li>
                                    <li title="Remover" rel="tooltip" class="inline icon delete_member_link ">
                                        <a class="pjax" href="<%= page_path(id: page.id) %>" data-method="delete" data-confirm="Tem certeza?">
                                            <i class="glyphicon glyphicon-remove"></i>
                                            <span style="display:none">Remover</span>
                                        </a>
                                    </li>
                            </ul></td>
                        </tr>
                    <% } %>
				</tbody>
			</table>
            <%= paginate @pages %>
		</div>
		</div>
	</div>

app/views/pages/list.html.erb
<div class="wrapper">
<div id="content" class="content-news" role="main">
<article>

<!-- Recent News ______________________________________-->
<div id="recent-news">
  <h2 style="border-bottom: 1px dotted #b2b2b2;">Notícias</h2>
  <%= paginate @news %>
  <div class="carousel-vert-no">
    <ul>
      <% @news.each{ |news| %>
          <li>
            <article class="recent-blog">
              <section class="date">
                <span class="day"><%= news.created_at.day %></span>
                <span class="month"><%= I18n.t("date.abbr_month_names")[news.created_at.month] %></span>
              </section>
              <figure>
                <a href="<%= news_path(id: news.id) %>"><img src="<%= news.main_image.url(:thumb) %>" alt="" /></a>
              </figure>
              <h3><a href="<%= news_path(id: news.id) %>"><%= truncate(news.title, length: 80) %></a></h3>
            </article>
          </li>
      <% } %>

    </ul>
  </div>
  <%= paginate @news %>
</div> <!-- END #recent-news -->
	
</article>
</div>
</div>

app/views/pages/new.html.erb
<div class="page-header">
  <div class="row">
    <div class="col-md-6 col-sm-6">
      <h1>Página</h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">

    <%= link_to "VOLTAR", :back, class: "new-btn" %>



    <div class="panel panel-default margin-panel">
      <!-- Default panel contents -->
      <div class="panel-heading">Nova Página</div>

      <div class="row">
        <%= render 'form' %>
      </div>

    </div>

  </div>
</div>

app/views/pages/show.html.erb
<div class="wrapper">
<div id="content" class="content-news" role="main">
<article id="post-1" class="post">

	<header class="entry-header">
		<!-- Post Image ______________________________________-->
		<div class="post-image">
					
		</div>	
	</header> <!-- END .entry-header -->

	<div class="entry-content">
		<!-- Heading ______________________________________-->

		<%= @page.content.html_safe %>


	</div><!-- END .entry-content -->
	<div class="clear"></div>
	
</article>



</div>
</div>